# AGENDA APP

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python_template-app
  namespace: production
  labels:
    app: python_template-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python_template-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python_template-app
    spec:
      containers:
        - name: python_template-app
          image: misoregistry.edgarluna.dev/images/python_template-production:latest
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
      imagePullSecrets:
        - name: regcred

---
kind: Service
apiVersion: v1
metadata:
  name: python_template-svc
  namespace: production
spec:
  type: NodePort
  selector:
    app: agenda-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001